platformName Android
automationName uiautomator2
deviceName RedMi A4 5G
udid 89f0fd14
autoGrantPermissions true
ignoreHiddenApiPolicyError true
noReset true
appPackage com.bigbasket.mobileapp
appActivity 